### ISSUE TITLE
When an error occurs the beforeAction hook of application is not executed

### ISSUE THREAD

**Issue by harianus** [postlight/lux#280]
The response body is then not readable by the browser when CORS-headers are being set in the `beforeAction`-hook.

I use this function to set the CORS-headers:

```js
import { Controller } from 'lux-framework';

class ApplicationController extends Controller {
  beforeAction = [
    function setCorsHeader(req, res) {
      res.setHeader('Access-Control-Allow-Origin', '*');
      res.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
    }
  ];
}

export default ApplicationController;
```

The browser will then return this message:

```
XMLHttpRequest cannot load http://localhost:4000/resourse. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 400.
```

**Comment by zacharygolba** [comment]
As discussed on [Gitter](https://gitter.im/postlight/lux), this is the expected behavior and we should not change this. However, it is important that you can gracefully handle requests that fail before entering the `ApplicationController`'s `beforeAction` hooks. I'm going to close this in favor of #282.
