### ISSUE TITLE
Don't want to use MySQL

### ISSUE THREAD

**Issue by sarikav1986** [postlight/lux#69]
Hi, 
I like framework and looks awesome. I don't want to use MySQL as I am writing service which calls another XML service via HTTP so don't need MySQL. How can I skip mySQL?

**Comment by zacharygolba** [comment]
Thanks!

Let me make sure I understand this issue correctly. Do you want to use a different database other than MySQL (i.e PostgreSQL, SQLite3) or do you want to use Lux to return JSON from another web service that handles the DB connection?

**Comment by sarikav1986** [comment]
I want to use Lux to return JSON from another web service that handles the DB connection?

**Comment by zacharygolba** [comment]
As much as I want you to use Lux on this project unfortunately this is not currently possible. 😞

I'm going to close this issue because this type of functionality is not was Lux is intended for. The integration between `Model`, `Controller`, and `Serializer` is what allows Lux to provide its unique set of features. It's hard to take the `Model` and database layer out of the equation because it's the foundation for the rest of the system.

In the future we may provide away to use an external service as a data source for the `Model` layer if enough user's request this feature. Somebody in the community may even write a plugin for this functionality. In the mean time I recommend using [Restify](http://restify.com/) or [Express](http://expressjs.com/).

If you want to chat more about this or have any questions feel free to post them in our [Gitter room](https://gitter.im/postlight/lux).

Thanks again for considering Lux on your project! 😃
