### ISSUE TITLE
model "hasMany" undefined error

### ISSUE THREAD

**Issue by JohnHawley** [postlight/lux#71]
**Lux beta7** | **Node v4.2.1** | **MariaDB v10.1.11**

I'm new to this. I'm also interested in contributing when I get my bearings.

I noticed this: 
on default npm install and after generating `user`, `post` and `account` models with CLI `resource` 

I took the `user` model from the guides:
```
class User extends Model {
  static hasOne = {
    account: {
      model: 'account',
      reverse: 'user'
    }
  };
  static hasMany = {
    posts: {
      model: 'post',
      reverse: 'author'
    }
  };
}
```

I get this lovely error when starting the server, and I'm not sure where I should look to debug it:
```
[5/12/16 7:48:48 PM] Starting Lux Server with 4 worker processes
{ [ORMError: Unknown property type: undefined]
  message: 'Unknown property type: undefined',
  code: 4,
  literalCode: 'NO_SUPPORT' }
```

**However**, when I remove the `hasMany` from the user model, everything seems to work as expected.

I've attempted this on 2 machines. Any _initial_ ideas on the reason for the error?

**Comment by zacharygolba** [comment]
Hey, thanks for using Lux.

> I'm new to this. I'm also interested in contributing when I get my bearings.

Looking forward to it! 😃 

--

The reason you are having this issue is because of the way the [node-orm2](https://github.com/dresende/node-orm2) based `Model` expects relationships to be defined.

In Lux v0.0.1-beta.7 (current version) defining relationships on your `Model` is only concerned about the `belongsTo` side of the relationship. So basically you could prevent this error by only defining the author-post relationship on the the `Post` model.

**Example:** 

```javascript
class Post extends Model {
  static hasOne = {
    author: {
      model: 'user',
      reverse: 'posts'
    }
  };
}
```

Even though you have only defined the relationship one way you will still be able to access `.posts` from `User` and you can still keep your serializer the way you would expect the `Model` relationships to work.

--

Although that will get rid of that error message, this is still counter-intuitive and not like the rest of the Lux API. That's why we built a custom orm specifically for Lux. #65 is about ready to be merged and will be released in the next version (`0.0.1-beta.8`). This will allow you to define relationships from both sides as you have in the example above. [Check out the test app in the knex branch](https://github.com/postlight/lux/tree/knex/test/test-app/app/models).

--

I'm going leave this issue open until #65 is merged and the next version is released. Let me know if you have any more questions about this.

--

*P.S*

If you have general questions that are not a potential bug or feature request feel free to join the Lux chat room on [Gitter](https://gitter.im/postlight/lux)!
